require 'lint_trap/version'
require 'json'
require 'colorize'
require 'awesome_print'

require 'lint_trap/es_linter'
require 'lint_trap/haml_linter'
require 'lint_trap/ruby_linter'
require 'lint_trap/scss_linter'
require 'lint_trap/processor'
